[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
	meta(title, desc): metadata for tests - short title and one-line description in Spanish